# Generated by Django 3.0.6 on 2020-06-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artiststationary',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=256)),
                ('category', models.CharField(default='', max_length=100)),
                ('image1', models.ImageField(default='', upload_to='myShop/images')),
                ('image2', models.ImageField(default='', upload_to='myShop/images')),
                ('image3', models.ImageField(default='', upload_to='myShop/images')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Desktopstationary',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=256)),
                ('category', models.CharField(default='', max_length=100)),
                ('image1', models.ImageField(default='', upload_to='myShop/images')),
                ('image2', models.ImageField(default='', upload_to='myShop/images')),
                ('image3', models.ImageField(default='', upload_to='myShop/images')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Electronicstationary',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=256)),
                ('category', models.CharField(default='', max_length=100)),
                ('image1', models.ImageField(default='', upload_to='myShop/images')),
                ('image2', models.ImageField(default='', upload_to='myShop/images')),
                ('image3', models.ImageField(default='', upload_to='myShop/images')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Filling_and_storage_stationary',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=256)),
                ('category', models.CharField(default='', max_length=100)),
                ('image1', models.ImageField(default='', upload_to='myShop/images')),
                ('image2', models.ImageField(default='', upload_to='myShop/images')),
                ('image3', models.ImageField(default='', upload_to='myShop/images')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Officestationary',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=256)),
                ('category', models.CharField(default='', max_length=100)),
                ('image1', models.ImageField(default='', upload_to='myShop/images')),
                ('image2', models.ImageField(default='', upload_to='myShop/images')),
                ('image3', models.ImageField(default='', upload_to='myShop/images')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paper_and_pad',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=256)),
                ('category', models.CharField(default='', max_length=100)),
                ('image1', models.ImageField(default='', upload_to='myShop/images')),
                ('image2', models.ImageField(default='', upload_to='myShop/images')),
                ('image3', models.ImageField(default='', upload_to='myShop/images')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Printing_material',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=256)),
                ('category', models.CharField(default='', max_length=100)),
                ('image1', models.ImageField(default='', upload_to='myShop/images')),
                ('image2', models.ImageField(default='', upload_to='myShop/images')),
                ('image3', models.ImageField(default='', upload_to='myShop/images')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Writtingstationary',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=256)),
                ('category', models.CharField(default='', max_length=100)),
                ('image1', models.ImageField(default='', upload_to='myShop/images')),
                ('image2', models.ImageField(default='', upload_to='myShop/images')),
                ('image3', models.ImageField(default='', upload_to='myShop/images')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
