# Generated by Django 3.0.6 on 2020-06-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0004_artiststationary_desktopstationary_electronicstationary_filling_and_storage_stationary_officestation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('amount', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=50000)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=120)),
                ('phone', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
