# Generated by Django 3.0.6 on 2020-06-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0006_auto_20200626_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artiststationary',
        ),
        migrations.DeleteModel(
            name='Desktopstationary',
        ),
        migrations.DeleteModel(
            name='Electronicstationary',
        ),
        migrations.DeleteModel(
            name='Filling_and_storage_stationary',
        ),
        migrations.DeleteModel(
            name='Paper_and_pad',
        ),
        migrations.DeleteModel(
            name='Printing_material',
        ),
        migrations.DeleteModel(
            name='Writtingstationary',
        ),
    ]
