# Generated by Django 3.0.6 on 2020-06-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0008_officestationary_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officestationary',
            old_name='type',
            new_name='secondary_category',
        ),
    ]
