# Generated by Django 3.0.6 on 2020-06-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0009_auto_20200626_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
