# Generated by Django 3.0.6 on 2020-06-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0012_auto_20200628_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=50000)),
                ('image', models.ImageField(default='', upload_to='myShop/images')),
            ],
        ),
    ]
