# Generated by Django 3.0.6 on 2020-06-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0013_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(default='', upload_to='myShop/images/'),
        ),
    ]
